AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura base para NearMex

Resources:
  NearMexInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ea87431b78a82070 
      Tags:
        - Key: Name
          Value: NearMex-Production-Server
      SecurityGroups:
        - !Ref NearMexSecurityGroup

  NearMexSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilitar trafico para SSH, API y Web
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0